version: "3.8"

services:
  eureka-server:
    build: ./eureka
    ports:
      - 8761:8761
    networks:
      - ms-network
    expose:
      - 8761
  gateway:
    build: ./gateway
    ports:
      - 8090:8090
    networks:
      - ms-network
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"
  blog:
    build: ./blog
    networks:
      - ms-network
  blog-user:
    build: ./blog-user
    networks:
      - ms-network
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3305:3306'
    networks:
      - ms-network
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - blog:/var/lib/mysql

volumes:
  blog:
networks:
  ms-network:
    driver: bridge